plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

require:
  - rubocop-yard

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 30
  CountRepeatedAttributes: false

Metrics/ClassLength:
  Max: 250
  CountAsOne:
    - heredoc
    - array
    - hash

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 30
  CountAsOne:
    - heredoc
    - array
    - hash

Metrics/ModuleLength:
  Max: 200
  CountAsOne:
    - heredoc
    - array
    - hash
  Exclude:
    - "lib/mq/rest/admin/commands.rb"

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Max: 12

Minitest/MultipleAssertions:
  Enabled: false

Style/Documentation:
  Enabled: true
  Exclude:
    - "test/**/*"
