plugins:
  - rubocop-minitest
  - rubocop-rake

require:
  - rubocop-yard

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "lib/mq/rest/admin/mapping.rb"

Metrics/BlockNesting:
  Exclude:
    - "lib/mq/rest/admin/mapping.rb"

Minitest/MultipleAssertions:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 12

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: true
  Exclude:
    - "test/**/*"
