[project]
repository-type = "library"
versioning-scheme = "library"
branching-model = "library-release"
release-model = "artifact-publishing"
primary-language = "ruby"

[ci]
versions = ["3.2", "3.3", "3.4"]
integration-tests = true

[markdownlint]
ignore = ["docs/site/docs"]

[publish]
release = true
docs = true

[dependencies]
vergil = "v2.0"
