name: Publish release

on:
  push:
    branches: [main]

permissions:
  attestations: write
  contents: write
  id-token: write
  pull-requests: write

jobs:
  publish:
    uses: wphillipmoore/standard-actions/.github/workflows/publish-release.yml@v1.5
    with:
      language: ruby
      container-tag: "3.4"
      registry-publish: true
    secrets: inherit
